#!/usr/bin/env node
/**
 * First-run setup: creates the Slack app, collects the two tokens, picks a
 * model, writes .env and starts the bot.
 *
 * Three of those steps stay in the browser because Slack offers no way around
 * them. Creating the app over the API needs a configuration token that is
 * itself generated by hand, so the create-app form is opened prefilled with our
 * manifest instead. App-level tokens have no API at all. And installing to a
 * workspace is an OAuth round trip wanting an HTTPS redirect this has nowhere
 * to serve from. So the job here is to put each of them one click away and to
 * check what comes back — not to pretend they can be automated.
 *
 * The sandbox is left out on purpose: this walks someone to a first working
 * bot, and that is `--sandbox=host`. Confining the agent's shell tools to a
 * container is the README's business, and is warned about at the end.
 */

import { spawn } from "node:child_process";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { builtinModels } from "@earendil-works/pi-ai/providers/all";
import { Input, matchesKey, ProcessTerminal, SelectList, Spacer, Text, TUI } from "@earendil-works/pi-tui";
import { WebClient } from "@slack/web-api";
import { parse as parseYaml, stringify as stringifyYaml } from "yaml";
import { listLocalModels } from "../llm.js";
import { renderEnv } from "./env.js";

const ROOT = path.resolve(fileURLToPath(import.meta.url), "..", "..", "..");
// The manifest ships beside this file, not with the harness at ROOT: it is the
// wizard's own, and only a hand setup reads it from the repository.
const MANIFEST = path.resolve(fileURLToPath(import.meta.url), "..", "slack-manifest.yaml");
const DEFAULT_BASE_URL = "http://localhost:1234";
const DEFAULT_WORKSPACE = "./workspace-example";
const DEFAULT_BOT_NAME = "pi-dad";
// Slack's own limit on an app's name, and the shorter of the two it applies.
const MAX_BOT_NAME = 35;

// --- presentation ------------------------------------------------------------

const paint = (code) => (process.env.NO_COLOR ? (text) => text : (text) => `\x1b[${code}m${text}\x1b[0m`);
const bold = paint("1");
const dim = paint("2");
const red = paint("31");
const green = paint("32");
const yellow = paint("33");
const cyan = paint("36");

// One line of the transcript. Text pads by a line above and below by default,
// which triple-spaces a wizard that is mostly prose, and renders an empty
// string as nothing at all — so blank lines have to be asked for as blank.
const line = (text) => (text ? new Text(text, 1, 0) : new Spacer(1));

// SelectList takes its styling as functions, and pi-tui ships no default set.
const SELECT_THEME = {
	selectedPrefix: cyan,
	selectedText: cyan,
	description: dim,
	scrollInfo: dim,
	noMatch: dim,
};

/** Thrown by the prompts on Escape, and by a declined confirmation. */
class Cancelled extends Error {}

/**
 * The transcript of the setup: each question is appended, answered, and then
 * replaced by a line recording what was chosen — so what stays on screen reads
 * back as a summary rather than as a form that has been filled in.
 */
class Wizard {
	constructor() {
		this.tui = new TUI(new ProcessTerminal());
		this.cancelPending = null;
		this.stopped = false;
		// The TUI puts the terminal in raw mode, where Ctrl+C no longer raises
		// SIGINT. The prompts handle it themselves, but one pressed between two
		// of them would otherwise be swallowed and leave no way out.
		this.tui.addInputListener((data) => {
			if (!matchesKey(data, "ctrl+c")) return;
			this.quit();
			return { consume: true };
		});
	}

	start() {
		this.tui.start();
	}

	stop() {
		if (this.stopped) return;
		this.stopped = true;
		this.tui.stop();
	}

	/** Appends a line to the transcript. */
	say(text = "") {
		this.tui.addChild(line(text));
		this.tui.requestRender();
	}

	/**
	 * Starts a step on a screen of its own, under `title`.
	 *
	 * One step at a time reads better than a transcript scrolling past the top,
	 * and each step's own ✔ lines still build up within its screen. What it
	 * costs is the record of the earlier steps, which the summary at the end
	 * gives back.
	 */
	screen(title) {
		this.tui.clear();
		this.tui.requestRender(true); // drops the diffing state, so the old screen goes
		this.say();
		this.say(bold(title));
	}

	/** Records an answered question, with the answer highlighted. */
	answered(question, answer) {
		this.say(`${green("✔")} ${question} ${bold(answer)}`);
	}

	/** Abandons the setup: unwinds through whichever prompt is waiting. */
	quit() {
		const cancel = this.cancelPending;
		this.cancelPending = null;
		if (cancel) {
			cancel(new Cancelled());
			return;
		}
		// Nothing is waiting on an answer — a check is in flight, say — so there
		// is no promise to reject and stopping has to be immediate.
		this.stop();
		console.log("\nSetup stopped.\n");
		process.exit(130);
	}

	// Shows a question with an interactive component under it, resolving once
	// the component reports an answer. Both come back off screen either way;
	// whoever asked decides what, if anything, is left in their place.
	#prompt(question, component, wire) {
		const label = line(bold(question));
		this.tui.addChild(label);
		this.tui.addChild(component);
		this.tui.setFocus(component);
		this.tui.requestRender();

		return new Promise((resolve, reject) => {
			const close = () => {
				this.cancelPending = null;
				this.tui.removeChild(label);
				this.tui.removeChild(component);
				this.tui.setFocus(null);
				this.tui.requestRender();
			};
			this.cancelPending = (error) => {
				close();
				reject(error);
			};
			wire((value) => {
				close();
				resolve(value);
			});
		});
	}

	/**
	 * Asks a question and returns the chosen item's `value`.
	 * @param items [{ value, label, description }], as SelectList takes them.
	 */
	async select(question, items) {
		const list = new SelectList(items, Math.min(items.length, 8), SELECT_THEME, { maxPrimaryColumnWidth: 36 });
		const chosen = await this.#prompt(`${question} ${dim("(↑↓ to move, enter to choose)")}`, list, (settle) => {
			list.onSelect = (item) => settle(item.value);
			list.onCancel = () => this.quit();
		});
		this.answered(question, items.find((item) => item.value === chosen).label);
		return chosen;
	}

	/**
	 * Asks for a line of text, re-asking until `check` accepts it.
	 * @param check (value) => problem string, or null when the value will do.
	 * @param fallback returned for an empty answer, for a question with a default.
	 * @param hint shown with the question but not with the answer, which is where
	 *   a note about the default would only be in the way.
	 * @param record how to show the answer in the transcript; by default as typed.
	 *   Tokens use it to keep the secret out of the summary — while one is being
	 *   pasted it does stay visible, since a paste that went wrong is the thing
	 *   most worth being able to see.
	 */
	async ask(question, { check, fallback, hint, record = (value) => value } = {}) {
		for (;;) {
			const input = new Input();
			const asked = hint ? `${question} ${dim(hint)}` : question;
			const typed = await this.#prompt(asked, input, (settle) => {
				input.onSubmit = (value) => settle(value.trim());
				input.onEscape = () => this.quit();
			});
			const value = typed || fallback;
			const problem = value ? check?.(value) : "Nothing entered.";
			if (!problem) {
				this.answered(question, record(value));
				return value;
			}
			this.say(`  ${red("✗")} ${problem}`);
		}
	}

	/**
	 * Asks for a token and checks it against Slack, re-asking until one works.
	 * @param verify (token) => { problem } when it is refused, anything else on success.
	 */
	async askToken(question, prefix, verify) {
		for (;;) {
			const token = await this.ask(question, {
				// Catching the wrong token here saves a round trip, and can name the
				// mix-up — the two are easy to swap — instead of reporting invalid_auth.
				check: (value) =>
					value.startsWith(prefix) ? null : `That starts with "${value.split("-")[0]}-", and this one starts with "${prefix}".`,
				record: mask,
			});
			let result;
			const problem = await this.working("Checking it with Slack", async () => {
				result = await verify(token);
				return result.problem;
			});
			if (!problem) return { token, ...result };
			this.say(dim("  Copy it again, or press Escape to give up."));
		}
	}

	/**
	 * Runs `work` behind a pending line that is replaced by its outcome.
	 * @param work () => problem string, or null when it worked.
	 */
	async working(what, work) {
		const pending = new Text(dim(`  … ${what}`), 1, 0);
		this.tui.addChild(pending);
		this.tui.requestRender();
		const problem = await work();
		pending.setText(problem ? `  ${red("✗")} ${problem}` : `  ${green("✔")} ${what}`);
		this.tui.requestRender();
		return problem;
	}
}

// --- Slack -------------------------------------------------------------------

/** Walks through creating the Slack app and returns both tokens, both checked. */
async function slackStep(ui) {
	const manifest = parseYaml(await fs.readFile(MANIFEST, "utf8"));

	// No screen() here: the first step shares the opening one, rather than wiping
	// the title away before it has been read.
	ui.say();
	ui.say(bold("Slack app"));
	ui.say("pi-dad needs an app of its own in your workspace, with the scopes in src/setup/slack-manifest.yaml.");
	ui.say();

	// The name comes first because it is the only real decision on this screen —
	// and because it is baked into the manifest the form is prefilled with, so it
	// has to be settled before anything opens. Asking it of someone who turns out
	// to have an app already is the cost of not opening with a question about
	// plumbing; their app keeps whatever name it was given.
	const name = await ui.ask("What should the bot be called?", {
		hint: `(enter for ${DEFAULT_BOT_NAME})`,
		fallback: DEFAULT_BOT_NAME,
		check: (value) => (value.length > MAX_BOT_NAME ? `Slack allows ${MAX_BOT_NAME} characters, and that is ${value.length}.` : null),
	});
	ui.say(dim(`  People will mention it as @${name}, and it is what it posts as.`));
	ui.say();

	const how = await ui.select("Create the app now?", [
		{ value: "open", label: "Open Slack in the browser", description: "the form comes prefilled" },
		{ value: "url", label: "Copy the link instead", description: "to open it on another machine" },
		{ value: "have", label: "I already have the app", description: "straight to the tokens; it keeps its own name" },
	]);

	if (how !== "have") {
		const createUrl = createAppUrl(manifest, name);
		if (how !== "open" || !(await openInBrowser(createUrl))) await handOverLink(ui, createUrl);
		else ui.say(dim("  Opened in your browser."));

		ui.say();
		ui.say(`Pick your workspace and press ${bold("Create")}. Leave the tab open — the next two steps are in it.`);
		// Something has to hold this screen: the instruction above is no use once
		// the next step has cleared it away.
		while (
			(await ui.select("Ready?", [
				{ value: "next", label: "The app exists, carry on" },
				{ value: "again", label: "Give me the link again", description: "if nothing opened" },
			])) === "again"
		) {
			await handOverLink(ui, createUrl);
		}
	}

	ui.screen("Slack tokens");
	ui.say("Two of them, both from the app's own settings page. They are checked here as they are pasted.");
	ui.say();
	ui.say(`${bold("1.")} Basic Information → App-Level Tokens → ${bold("Generate Token and Scopes")}.`);
	ui.say(`   Name it anything, add the ${cyan("connections:write")} scope, generate it, and copy the token.`);
	const app = await ui.askToken("App-level token:", "xapp-", verifyAppToken);

	ui.say();
	ui.say(`${bold("2.")} Install App → OAuth Tokens → ${bold("Install to")} (or ${bold("Reinstall to")}) your workspace → Allow.`);
	ui.say(`   ${yellow("Press it even if a Bot User OAuth Token is already shown there:")} one issued before the`);
	ui.say("   app's current scopes connects perfectly and then never answers.");
	ui.say("   Then copy the Bot User OAuth Token from that box.");
	const bot = await ui.askToken("Bot token:", "xoxb-", (token) => verifyBotToken(token, manifest.oauth_config.scopes.bot));

	return { appToken: app.token, botToken: bot.token, botName: bot.name, teamName: bot.team };
}

/**
 * The link to Slack's create-app form, prefilled with the manifest under the
 * chosen name. Slack takes the manifest as a query parameter, which leaves the
 * user with a workspace to pick and a button to press.
 *
 * Rebuilding it through the YAML writer rather than by substitution loses the
 * file's comments, which the form has no use for anyway, and in exchange a name
 * with a colon or a quote in it can't turn the manifest into something that
 * doesn't parse.
 */
function createAppUrl(manifest, name) {
	const named = { ...manifest, display_information: { ...manifest.display_information, name } };
	named.features = { ...manifest.features, bot_user: { ...manifest.features.bot_user, display_name: name } };
	return `https://api.slack.com/apps?new_app=1&manifest_yaml=${encodeURIComponent(stringifyYaml(named))}`;
}

/** The one call an app-level token is for, used here only to prove it works. */
async function verifyAppToken(token) {
	try {
		const response = await fetch("https://slack.com/api/apps.connections.open", {
			method: "POST",
			headers: { authorization: `Bearer ${token}`, "content-type": "application/x-www-form-urlencoded" },
		});
		const body = await response.json();
		if (body.ok) return {};
		// What a bot token pasted here reports; say what it means.
		if (body.error === "not_allowed_token_type") return { problem: "That is not an app-level token." };
		return { problem: `Slack rejected it: ${body.error}` };
	} catch (error) {
		return { problem: `Couldn't reach Slack: ${error.message}` };
	}
}

/**
 * Checks the bot token, that it carries the scopes the manifest asks for, and
 * in passing learns the identity it will post as.
 *
 * The scope check is the one that earns its keep. Slack shows a Bot User OAuth
 * Token on the Install App page from an earlier install, before the current
 * scopes have been granted — copy that one and everything looks right: it
 * authenticates, the bot connects, and it then answers nothing, because the
 * events never arrive. Reinstalling is what reissues it. Slack reports what a
 * token was actually granted in a response header, which the SDK unpacks into
 * response_metadata, so the mismatch is catchable here rather than in Slack.
 */
async function verifyBotToken(token, requiredScopes) {
	let auth;
	try {
		auth = await new WebClient(token).auth.test();
	} catch (error) {
		const reason = error.data?.error ?? error.message;
		if (reason === "invalid_auth") return { problem: "Slack rejected it. Is the app installed to the workspace?" };
		return { problem: `Slack rejected it: ${reason}` };
	}

	// Absent header: nothing to compare against, so let it through rather than
	// refuse a token that may well be fine.
	const granted = auth.response_metadata?.scopes;
	const missing = granted ? requiredScopes.filter((scope) => !granted.includes(scope)) : [];
	if (missing.length) {
		return { problem: `Granted before the app had ${missing.join(", ")}. Reinstall the app, then copy the token again.` };
	}
	return { name: auth.user, team: auth.team };
}

/** Opens a URL in the default browser. False if there was nothing to open it with. */
function openInBrowser(url) {
	const command = process.platform === "darwin" ? "open" : process.platform === "win32" ? "start" : "xdg-open";
	return new Promise((resolve) => {
		const child = spawn(command, [url], { stdio: "ignore", detached: true, shell: process.platform === "win32" });
		child.on("error", () => resolve(false));
		child.on("spawn", () => {
			child.unref();
			resolve(true);
		});
	});
}

/**
 * Gets the link into the user's hands without a browser. The clipboard first,
 * because the manifest travels inside the URL: it runs to a couple of thousand
 * characters, and copying that back out of a wrapped terminal block by hand is
 * how a truncated manifest ends up pasted into Slack.
 */
async function handOverLink(ui, url) {
	if (await copyToClipboard(url)) {
		ui.say(dim("  Copied to your clipboard — paste it into a browser."));
		return;
	}
	ui.say(`  ${yellow("!")} Nothing to copy with here. The link, in one piece:`);
	ui.say(dim(`  ${url}`));
}

// Whatever this platform reads standard input into the clipboard with; on Linux
// it depends on the display server, so both are tried.
const CLIPBOARD_COMMANDS =
	process.platform === "darwin"
		? [["pbcopy", []]]
		: process.platform === "win32"
			? [["clip", []]]
			: [
					["wl-copy", []],
					["xclip", ["-selection", "clipboard"]],
				];

async function copyToClipboard(text) {
	for (const [command, args] of CLIPBOARD_COMMANDS) {
		const copied = await new Promise((resolve) => {
			const child = spawn(command, args, { stdio: ["pipe", "ignore", "ignore"] });
			child.on("error", () => resolve(false)); // not installed
			child.on("close", (code) => resolve(code === 0));
			child.stdin.on("error", () => {}); // the EPIPE that comes with it
			child.stdin.end(text);
		});
		if (copied) return true;
	}
	return false;
}

// --- model, workspace, .env --------------------------------------------------

/** Picks the provider, endpoint and model id to answer with. */
async function modelStep(ui) {
	ui.screen("Model");
	ui.say("Everything the agent reads goes to the model, so a workspace holding anything sensitive wants a local one.");
	ui.say();

	const provider = await ui.select("Which model should it use?", [
		{ value: "local", label: "A local server", description: "LM Studio, oMLX, anything speaking Anthropic messages" },
		{ value: "anthropic", label: "Anthropic", description: "needs an API key, and sends your data to them" },
	]);
	return provider === "local" ? await localModelStep(ui) : await anthropicModelStep(ui);
}

async function localModelStep(ui) {
	let baseUrl = DEFAULT_BASE_URL;
	for (;;) {
		let models;
		const problem = await ui.working(`Asking ${baseUrl} what it has`, async () => {
			models = await listChatModels(baseUrl);
			if (!models) return `Nothing answered at ${baseUrl}. Is the server running?`;
			return models.length ? null : "The server answered, but has no model to answer with.";
		});

		if (!problem) {
			// The id has to be given exactly as the server names it, and picking
			// from its own list is the only way to be sure of that: some servers
			// answer for an unknown id with whatever is loaded, so a typo shows up
			// as subtly wrong replies rather than as an error.
			const model = await ui.select(
				"Which model?",
				models.map(({ id, loaded }) => ({
					value: id,
					label: id,
					// Worth knowing which one answers straight away: a cold model is
					// loaded on the first message, which can take a while.
					description: loaded === undefined ? undefined : loaded ? "in memory" : "not loaded yet",
				})),
			);
			return { provider: "local", model, baseUrl };
		}

		const next = await ui.select("What now?", [
			{ value: "retry", label: "Try again", description: "after starting the server" },
			{ value: "url", label: "It's on another address", description: "give a different URL" },
			{ value: "anthropic", label: "Use Anthropic instead", description: "a cloud model" },
		]);
		if (next === "anthropic") return await anthropicModelStep(ui);
		if (next === "url") {
			baseUrl = await ui.ask("Base URL:", {
				hint: `(enter for ${DEFAULT_BASE_URL})`,
				fallback: DEFAULT_BASE_URL,
				check: (value) => (URL.parse(value) ? null : "That isn't a URL."),
			});
		}
	}
}

/**
 * The models a local server can actually hold a conversation with, as
 * `[{ id, loaded }]`, or null when nothing answers.
 *
 * The OpenAI-compatible list is ids and nothing else, so an embedding model is
 * indistinguishable there from a chat one — and choosing it is a mistake that
 * surfaces only at the first message. LM Studio serves a second, richer list
 * saying which is which and what is already in memory, so that one is tried
 * first; anything else falls back to the plain list, unannotated.
 */
async function listChatModels(baseUrl) {
	try {
		const entries = (await (await fetch(new URL("/api/v0/models", baseUrl))).json()).data;
		if (Array.isArray(entries) && entries.length && entries.every((entry) => entry.id && entry.type)) {
			return entries
				.filter((entry) => entry.type !== "embeddings")
				.map((entry) => ({ id: entry.id, loaded: entry.state === "loaded" }));
		}
	} catch {
		// Not LM Studio, or not offering it. The plain list will do.
	}
	return (await listLocalModels(baseUrl))?.map((id) => ({ id, loaded: undefined }));
}

async function anthropicModelStep(ui) {
	const catalog = builtinModels()
		.getModels("anthropic")
		.map((model) => ({ value: model.id, label: model.id, description: model.name }));
	const model = await ui.select("Which model?", catalog);

	// Already exported: leave it in the environment rather than copy a live key
	// into a file the user didn't choose to put it in.
	if (process.env.ANTHROPIC_API_KEY) {
		ui.say(dim("  Using the ANTHROPIC_API_KEY already in your environment."));
		return { provider: "anthropic", model };
	}
	const apiKey = await ui.ask("Anthropic API key:", { record: mask });
	return { provider: "anthropic", model, apiKey };
}

/** Picks the workspace directory the skills are read from. */
async function workspaceStep(ui) {
	ui.screen("Workspace");
	ui.say(`Where its skills live. ${DEFAULT_WORKSPACE} ships with pi-dad and has one skill to try it out with.`);
	ui.say();

	const workspace = await ui.ask("Workspace directory:", {
		hint: `(enter for ${DEFAULT_WORKSPACE})`,
		// A quote in the path has no form both sh and dotenv read the same way,
		// so it can't be written to .env — see quote() in env.js.
		check: (value) => (value.includes("'") ? "A path with a single quote in it can't be written to .env." : null),
		fallback: DEFAULT_WORKSPACE,
	});

	const missing = await fs.stat(path.resolve(ROOT, workspace)).then(
		(stat) => !stat.isDirectory(),
		() => true,
	);
	if (missing) ui.say(`  ${yellow("!")} There is no directory there yet. pi-dad will start, and find no skills.`);
	return workspace;
}

/**
 * Writes .env, keeping whatever an existing one already says. Confirmed first:
 * it is the only step that changes anything on disk.
 */
async function writeStep(ui, values) {
	const envPath = path.join(ROOT, ".env");
	const existing = await fs.readFile(envPath, "utf8").catch(() => null);

	ui.screen("Save");
	ui.say(
		existing
			? `${envPath} already exists. Its other settings are kept; the ones asked about here are replaced.`
			: `Everything above goes into ${envPath}.`,
	);
	ui.say();

	const confirmed = await ui.select(existing ? "Update it?" : "Write it?", [
		{ value: "yes", label: "Yes" },
		{ value: "no", label: "No, stop here", description: "nothing has been written yet" },
	]);
	if (confirmed === "no") throw new Cancelled();

	const template = existing ?? (await fs.readFile(path.join(ROOT, ".env.example"), "utf8"));
	await fs.writeFile(envPath, renderEnv(template, values), { mode: 0o600 });
	// The mode above only applies to a file being created, and this one now holds
	// live tokens whether it was just created or not.
	await fs.chmod(envPath, 0o600);
	ui.say(`  ${green("✔")} Written.`);
}

/** Offers to start the bot, and returns the exit code to leave with. */
async function launchStep(ui, values) {
	const mention = `@${values.botName}`;
	ui.screen("Ready");
	// The steps above are each on a screen of their own by now, so this is the
	// only place the whole of what was chosen can be seen at once.
	for (const [label, value] of [
		["Posting as", `${mention} in ${values.teamName}`],
		["Model", `${values.provider}/${values.model}${values.provider === "local" ? ` at ${values.baseUrl}` : ""}`],
		["Workspace", values.workspace],
		["Settings", path.join(ROOT, ".env")],
	]) {
		ui.say(`  ${dim(label.padEnd(11))}${value}`);
	}

	ui.say();
	ui.say(bold("It won't answer anywhere until you invite it."));
	ui.say(`Open Slack, go to a channel it should work in, and send ${cyan(`/invite ${mention}`)} as a message.`);
	// Only worth suggesting where that skill is actually installed: past a first
	// run the workspace is usually a repo of the reader's own.
	const hasWhoami = await fs.stat(path.resolve(ROOT, values.workspace, "skills", "whoami")).then(
		() => true,
		() => false,
	);
	if (hasWhoami) {
		ui.say(`Then ask it ${cyan(`${mention} who am I?`)} — that runs the example skill, which reports who is`);
		ui.say("asking and from where. A sensible answer means the model, the skills and the scopes all work.");
	} else {
		ui.say(`Then talk to it by name: ${cyan(`${mention} hello`)}.`);
	}
	ui.say(`It answers direct messages with no invite too — find it under ${bold("Apps")} at the bottom of the`);
	ui.say(`sidebar, or search for ${bold(mention)}.`);
	ui.say();
	ui.say(`To start it again later: ${cyan("npm run start:host")}.`);
	ui.say();
	ui.say(`${yellow("!")} With no sandbox, the agent's bash, read, write and edit tools run on this machine, as you,`);
	ui.say('  over every file you can reach. Read "Create the sandbox container" in the README before');
	ui.say("  pointing it at anything that matters.");
	ui.say();

	const start = await ui.select("Start it now?", [
		{ value: "yes", label: "Yes", description: "Ctrl+C stops it" },
		{ value: "no", label: "No, I'm done" },
	]);
	if (start === "no") return 0;

	const args = ["--sandbox=host", `--provider=${values.provider}`, `--model=${values.model}`];
	if (values.provider === "local") args.push(`--base-url=${values.baseUrl}`);
	args.push(values.workspace);

	ui.stop();
	// Said again on the way out: the bot's own startup output scrolls the screen
	// above away, and this is the one thing still left to do by hand.
	console.log(`\nInvite it where it should answer: /invite ${mention}`);
	console.log(hasWhoami ? `Then try: ${mention} who am I?\n` : "");
	console.log(`Starting: node src/main.js ${args.join(" ")}\n`);
	// The tokens are passed in the environment rather than by sourcing the file
	// just written, so this starts the same way whatever shell is in use.
	return await new Promise((resolve) => {
		const child = spawn(process.execPath, [path.join(ROOT, "src", "main.js"), ...args], {
			cwd: ROOT,
			stdio: "inherit",
			env: {
				...process.env,
				DAD_SLACK_APP_TOKEN: values.appToken,
				DAD_SLACK_BOT_TOKEN: values.botToken,
				...(values.apiKey ? { ANTHROPIC_API_KEY: values.apiKey } : {}),
			},
		});
		child.on("close", (code) => resolve(code ?? 0));
	});
}

/** Shows enough of a secret to tell which one it is, and no more. */
function mask(secret) {
	return secret.length > 16 ? `${secret.slice(0, 9)}…${secret.slice(-4)}` : "…";
}

// --- main --------------------------------------------------------------------

const ui = new Wizard();
ui.start();
let exitCode = 0;
try {
	ui.screen("pi-dad setup");
	ui.say("A Slack app, a model, a workspace — then it runs. Nothing is written until the end; Ctrl+C to stop.");

	const slack = await slackStep(ui);
	ui.say(`  ${green("✔")} It will post as ${bold(`@${slack.botName}`)} in ${bold(slack.teamName)}.`);

	const model = await modelStep(ui);
	const workspace = await workspaceStep(ui);

	await writeStep(ui, {
		DAD_SLACK_APP_TOKEN: slack.appToken,
		DAD_SLACK_BOT_TOKEN: slack.botToken,
		DAD_PROVIDER: model.provider,
		DAD_MODEL: model.model,
		// Written empty for a cloud provider, where main.js refuses the flag, so
		// that a URL left over from an earlier run doesn't get passed to it.
		DAD_BASE_URL: model.baseUrl ?? "",
		DAD_WORKSPACE: workspace,
		ANTHROPIC_API_KEY: model.apiKey,
	});

	exitCode = await launchStep(ui, { ...slack, ...model, workspace });
} catch (error) {
	ui.stop();
	if (error instanceof Cancelled) {
		console.log("\nSetup stopped. Run `npm run setup` again to take it from the top.\n");
		exitCode = 130;
	} else {
		console.error(`\n${error.stack}\n`);
		exitCode = 1;
	}
}
ui.stop();
process.exit(exitCode);
